.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "OPENALIAS\.RS" "1" "April 2018" "openalias.rs developers" ""
.
.SH "NAME"
\fBopenalias\.rs\fR \- Look up and parse OpenAlias data
.
.SH "SYNOPSIS"
\fBopenalias\fR <OPEN_ALIAS>\.\.\. \fIOPTIONS\fR
.
.SH "DESCRIPTION"
Look up and parse OpenAlias data\.
.
.P
OpenAlias is an open DNS\-based name to cryptocurrency address mapping format\.
.
.SH "OPTIONS"
<OPEN_ALIAS>\.\.\.
.
.IP "" 4
.
.nf

FQDN or email\-style aliases to look up addresses for\.
.
.fi
.
.IP "" 0
.
.P
\-v \-\-verbose
.
.IP "" 4
.
.nf

Print more data about what\'s happenning to stderr\.

Default: don\'t\.
.
.fi
.
.IP "" 0
.
.P
\-r \-\-raw
.
.IP "" 4
.
.nf

Print just the record text\.

Default: pretty\-printing\.
.
.fi
.
.IP "" 0
.
.P
\-c \-\-currency=CURRENCY\.\.\.
.
.IP "" 4
.
.nf

Limit results to specified currencies\.
.
.fi
.
.IP "" 0
.
.SH "EXAMPLES"
\fBopenalias nabijaczleweli\.xyz donate\.getmonero\.org\fR
.
.IP "" 4
.
.nf

Addresses of nabijaczleweli\.xyz:
  btc:
    nabijaczleweli
    1CgLs6CxXMAY4Pj4edQq5vyaFoP9NdqVKH

Addresses of donate\.getmonero\.org:
  xmr:
    Monero Development
    44AFFq5kSiGBoZ4NMDwYtN18obc8AemS33DBLWs3H7otXft3
      XjrpDtQGv7SqSsaBYBb98uNbr2VBBEt7f2wfn3RVGQBEP3A
    Donation to Monero Core Team
  btc:
    Monero Development
    1KTexdemPdxSBcG55heUuTjDRYqbC5ZL8H
    Donation to Monero Core Team
.
.fi
.
.IP "" 0
.
.P
\fBopenalias \-rv nabijaczleweli\.xyz donate@getmonero\.org\fR
.
.IP "" 4
.
.nf

Looking up nabijaczleweli\.xyz\.\.\.
Addresses for nabijaczleweli\.xyz:
  oa1:btc recipient_address=1CgLs6CxXMAY4Pj4edQq5vyaFoP9NdqVKH;
          recipient_name=nabijaczleweli;

Looking up donate@getmonero\.org\.\.\.
Addresses for donate@getmonero\.org:
  oa1:xmr recipient_address=44AFFq5kSiGBoZ4NMDwYtN18obc8AemS33DBLWs3H7otXft3
                              XjrpDtQGv7SqSsaBYBb98uNbr2VBBEt7f2wfn3RVGQBEP3A;
          recipient_name=Monero Development;
          tx_description=Donation to Monero Core Team;
  oa1:btc recipient_address=1KTexdemPdxSBcG55heUuTjDRYqbC5ZL8H;
          recipient_name=Monero Development;
          tx_description=Donation to Monero Core Team;
.
.fi
.
.IP "" 0
.
.P
\fBopenalias \-cxmr \-c doge nabijaczleweli\.xyz donate\.getmonero\.org\fR
.
.IP "" 4
.
.nf

No xmr, nor doge addresses found for nabijaczleweli\.xyz\.

Addresses of donate\.getmonero\.org:
  xmr:
    Monero Development
    44AFFq5kSiGBoZ4NMDwYtN18obc8AemS33DBLWs3H7otXft3
      XjrpDtQGv7SqSsaBYBb98uNbr2VBBEt7f2wfn3RVGQBEP3A
    Donation to Monero Core Team
.
.fi
.
.IP "" 0
.
.SH "AUTHOR"
Written by nabijaczleweli <\fInabijaczleweli@gmail\.com\fR>
.
.SH "REPORTING BUGS"
<\fIhttps://github\.com/nabijaczleweli/openalias\.rs/issues\fR>
.
.SH "SEE ALSO"
<\fIhttps://openalias\.org\fR>
.
.br
<\fIhttps://github\.com/nabijaczleweli/openalias\.rs\fR>
