.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "OPENALIAS\.RS" "1" "September 2017" "openalias.rs developers" ""
.
.SH "NAME"
\fBopenalias\.rs\fR \- Securely look up and parse OpenAlias data
.
.SH "SYNOPSIS"
\fBopenalias\fR <OPEN_ALIAS>\.\.\.
.
.SH "DESCRIPTION"
Securely look up and parse OpenAlias data\.
.
.P
OpenAlias is an open DNS\-based name to cryptocurrency address mapping format\.
.
.P
\fBopenalias\.rs\fR utilises DNSCrypt and official OpenAlias DNS servers in order to ensure that your lookups are safe\.
.
.SH "OPTIONS"
<OPEN_ALIAS>\.\.\.
.
.IP "" 4
.
.nf

FQDN or email\-style aliases to look up addresses for\.
.
.fi
.
.IP "" 0
.
.SH "EXAMPLES"
\fBopenalias nabijaczleweli\.xyz donate\.getmonero\.org\fR
.
.IP "" 4
.
.nf

TODO
.
.fi
.
.IP "" 0
.
.SH "AUTHOR"
Written by nabijaczleweli <\fInabijaczleweli@gmail\.com\fR>
.
.SH "REPORTING BUGS"
<\fIhttps://github\.com/nabijaczleweli/openalias\.rs/issues\fR>
.
.SH "SEE ALSO"
<\fIhttps://openalias\.org\fR>
.
.br
<\fIhttps://github\.com/nabijaczleweli/openalias\.rs\fR>
