(function() {var implementors = {};
implementors["log"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/hash/trait.Hash.html\" title=\"trait core::hash::Hash\">Hash</a> for <a class=\"enum\" href=\"log/enum.Level.html\" title=\"enum log::Level\">Level</a>",synthetic:false,types:["log::Level"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/hash/trait.Hash.html\" title=\"trait core::hash::Hash\">Hash</a> for <a class=\"enum\" href=\"log/enum.LevelFilter.html\" title=\"enum log::LevelFilter\">LevelFilter</a>",synthetic:false,types:["log::LevelFilter"]},{text:"impl&lt;'a&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/hash/trait.Hash.html\" title=\"trait core::hash::Hash\">Hash</a> for <a class=\"struct\" href=\"log/struct.Metadata.html\" title=\"struct log::Metadata\">Metadata</a>&lt;'a&gt;",synthetic:false,types:["log::Metadata"]},{text:"impl&lt;'a&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/hash/trait.Hash.html\" title=\"trait core::hash::Hash\">Hash</a> for <a class=\"struct\" href=\"log/struct.MetadataBuilder.html\" title=\"struct log::MetadataBuilder\">MetadataBuilder</a>&lt;'a&gt;",synthetic:false,types:["log::MetadataBuilder"]},];
implementors["openalias"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/hash/trait.Hash.html\" title=\"trait core::hash::Hash\">Hash</a> for <a class=\"struct\" href=\"openalias/struct.Options.html\" title=\"struct openalias::Options\">Options</a>",synthetic:false,types:["openalias::options::Options"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/hash/trait.Hash.html\" title=\"trait core::hash::Hash\">Hash</a> for <a class=\"struct\" href=\"openalias/struct.CryptoAddress.html\" title=\"struct openalias::CryptoAddress\">CryptoAddress</a>",synthetic:false,types:["openalias::crypto_addr::CryptoAddress"]},];
implementors["resolve"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/hash/trait.Hash.html\" title=\"trait core::hash::Hash\">Hash</a> for <a class=\"struct\" href=\"resolve/record/struct.A.html\" title=\"struct resolve::record::A\">A</a>",synthetic:false,types:["resolve::record::A"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/hash/trait.Hash.html\" title=\"trait core::hash::Hash\">Hash</a> for <a class=\"struct\" href=\"resolve/record/struct.AAAA.html\" title=\"struct resolve::record::AAAA\">AAAA</a>",synthetic:false,types:["resolve::record::AAAA"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/hash/trait.Hash.html\" title=\"trait core::hash::Hash\">Hash</a> for <a class=\"struct\" href=\"resolve/record/struct.CName.html\" title=\"struct resolve::record::CName\">CName</a>",synthetic:false,types:["resolve::record::CName"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/hash/trait.Hash.html\" title=\"trait core::hash::Hash\">Hash</a> for <a class=\"struct\" href=\"resolve/record/struct.Mx.html\" title=\"struct resolve::record::Mx\">Mx</a>",synthetic:false,types:["resolve::record::Mx"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/hash/trait.Hash.html\" title=\"trait core::hash::Hash\">Hash</a> for <a class=\"struct\" href=\"resolve/record/struct.Ns.html\" title=\"struct resolve::record::Ns\">Ns</a>",synthetic:false,types:["resolve::record::Ns"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/hash/trait.Hash.html\" title=\"trait core::hash::Hash\">Hash</a> for <a class=\"struct\" href=\"resolve/record/struct.Ptr.html\" title=\"struct resolve::record::Ptr\">Ptr</a>",synthetic:false,types:["resolve::record::Ptr"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/hash/trait.Hash.html\" title=\"trait core::hash::Hash\">Hash</a> for <a class=\"struct\" href=\"resolve/record/struct.Soa.html\" title=\"struct resolve::record::Soa\">Soa</a>",synthetic:false,types:["resolve::record::Soa"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/hash/trait.Hash.html\" title=\"trait core::hash::Hash\">Hash</a> for <a class=\"struct\" href=\"resolve/record/struct.Srv.html\" title=\"struct resolve::record::Srv\">Srv</a>",synthetic:false,types:["resolve::record::Srv"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/hash/trait.Hash.html\" title=\"trait core::hash::Hash\">Hash</a> for <a class=\"struct\" href=\"resolve/record/struct.Txt.html\" title=\"struct resolve::record::Txt\">Txt</a>",synthetic:false,types:["resolve::record::Txt"]},];
implementors["vec_map"] = [{text:"impl&lt;V:&nbsp;<a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/hash/trait.Hash.html\" title=\"trait core::hash::Hash\">Hash</a>&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/hash/trait.Hash.html\" title=\"trait core::hash::Hash\">Hash</a> for <a class=\"struct\" href=\"vec_map/struct.VecMap.html\" title=\"struct vec_map::VecMap\">VecMap</a>&lt;V&gt;",synthetic:false,types:["vec_map::VecMap"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
